/*
* BANCO
*/

CREATE DATABASE BD_FASTBEATS
USE BD_FASTBEATS

/*
* TABELAS
*/

CREATE TABLE TB_FUNCIONARIO (
CPF_FUNC VARCHAR (14) PRIMARY KEY,
NOME_FUNC VARCHAR (100) NOT NULL,
END_FUNC VARCHAR (100) ,
TEL_FUNC VARCHAR (13), 
CEL_FUNC VARCHAR (14),
RG_FUNC VARCHAR (13) ,
EMAIL VARCHAR(200),
CARGO VARCHAR (50), 
DATA_NASC_FUNC VARCHAR (10),
LOCAL_FOTO_FUNC VARCHAR (255)
)
INSERT INTO TB_FUNCIONARIO (CPF_FUNC,NOME_FUNC) VALUES ('11111111111','Administrador')

CREATE TABLE TB_PERSONALIZACAO(
CPF_FUNC VARCHAR(14)PRIMARY KEY REFERENCES TB_FUNCIONARIO(CPF_FUNC),
TEMA INT,
COR INT
)
INSERT INTO TB_PERSONALIZACAO VALUES('11111111111',1,4)

CREATE TABLE TB_LOGIN (
USUARIO VARCHAR (50) PRIMARY KEY,
SENHA VARCHAR (50) NOT NULL,
NIVEL_ACESSO INT NOT NULL,
RECUP_SENHA VARCHAR(50),
ATIVO BIT,
CPF_FUNC VARCHAR (14) REFERENCES TB_FUNCIONARIO (CPF_FUNC)
)
INSERT INTO TB_LOGIN VALUES ('ADMIN','ADMIN',0,NULL,1,'11111111111')

CREATE TABLE TB_CLIENTE (
CPF_CLI VARCHAR (14) PRIMARY KEY,
NOME_CLI VARCHAR (100),
RG_CLI VARCHAR (50),
TEL_CLI VARCHAR (15),
CEL_CLI VARCHAR (15)
)
INSERT INTO TB_CLIENTE(CPF_CLI,NOME_CLI) VALUES ('0','Visitante')


  

CREATE TABLE TB_GENERO (
GENERO VARCHAR (50) PRIMARY KEY
)

CREATE TABLE TB_ARTISTA (
COD_ARTISTA INT PRIMARY KEY IDENTITY (1,1),
ARTISTA VARCHAR (100) NOT NULL,
TEL_EMPRESA VARCHAR (15),
EMAIL_EMPRESA VARCHAR (100),
GENERO VARCHAR (50) REFERENCES TB_GENERO (GENERO),
NOME_EMPRESA VARCHAR (100)
)

CREATE TABLE TB_EVENTO (
COD_EVENTO INT PRIMARY KEY IDENTITY (1,1),
NOME_EVENTO VARCHAR (100) NOT NULL,
DESCRICAO VARCHAR (255),
DATA_EVENTO DATE
)

CREATE TABLE TB_EVENTO_ARTISTA (
COD_EVENTO_ARTISTA INT PRIMARY KEY IDENTITY (1,1),
COD_ARTISTA INT REFERENCES TB_ARTISTA (COD_ARTISTA),
COD_EVENTO INT REFERENCES TB_EVENTO (COD_EVENTO)
)

CREATE TABLE TB_AGENDA (
COD_AGENDA INT PRIMARY KEY IDENTITY (1,1),
COD_EVENTO INT REFERENCES TB_EVENTO (COD_EVENTO) NOT NULL,
PRECO_HOMEM_VIP MONEY,
PRECO_HOMEM_PISTA MONEY,
PRECO_MULHER_VIP MONEY,
PRECO_MULHER_PISTA MONEY,
DATA_HORA_INICIO DATETIME,
DATA_HORA_FIM DATETIME
)

CREATE TABLE TB_RECEPCAO (
COD_RECEPCAO INT PRIMARY KEY IDENTITY (1,1),
CPF_FUNC VARCHAR (14) REFERENCES TB_FUNCIONARIO (CPF_FUNC) NOT NULL,
DESCR_COMPRA VARCHAR (20),
PRECO MONEY,
DATA_RECEPCAO VARCHAR(10),
COD_AGENDA INT REFERENCES TB_AGENDA (COD_AGENDA)
)


CREATE TABLE TB_COMANDA (
COD_COMANDA INT PRIMARY KEY
)

CREATE TABLE TB_UTILIDADE_COMANDA (
COD_UTILIDADE_COMANDA INT PRIMARY KEY IDENTITY(1,1),
COD_COMANDA INT REFERENCES TB_COMANDA (COD_COMANDA),
CPF_CLI VARCHAR (14) REFERENCES TB_CLIENTE (CPF_CLI),
COD_RECEPCAO INT REFERENCES TB_RECEPCAO (COD_RECEPCAO),
VALOR_TOTAL MONEY,
ATIVO BIT
)



CREATE TABLE TB_CAIXA (
COD_CAIXA INT PRIMARY KEY IDENTITY(1,1),
CPF_FUNC VARCHAR (14) REFERENCES TB_FUNCIONARIO (CPF_FUNC),
VALOR_TOTAL MONEY,
DATA DATE
)

CREATE TABLE TB_COMANDA_CAIXA (
COD_COMANDA_CAIXA INT PRIMARY KEY IDENTITY(1,1),
COD_CAIXA INT REFERENCES TB_CAIXA(COD_CAIXA),
COD_UTILIDADE_COMANDA INT REFERENCES TB_UTILIDADE_COMANDA (COD_UTILIDADE_COMANDA)
)


CREATE TABLE TB_FORMA_PAGAMENTO (
FORMA_PAGAMENTO VARCHAR (30) PRIMARY KEY
)

CREATE TABLE TB_PAGAMENTO (
COD_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
FORMA_PAGAMENTO VARCHAR (30) REFERENCES TB_FORMA_PAGAMENTO (FORMA_PAGAMENTO),
VALOR MONEY,
COD_CAIXA INT REFERENCES TB_CAIXA (COD_CAIXA)
)


CREATE TABLE TB_PRODUTO (
COD_PRODUTO INT PRIMARY KEY,
NOME_PRODUTO VARCHAR (100) NOT NULL,
QTD_PRODUTO INT NOT NULL,
QTD_MINIMA_PRODUTO INT,
PRECO_CUSTO_UNIDADE MONEY,
PRECO_VENDA MONEY
)

CREATE TABLE TB_CARDAPIO (
COD_CARDAPIO INT PRIMARY KEY IDENTITY (1,1),
NOME_PROD_CARDAPIO VARCHAR (255) NOT NULL,
PRECO_PROD_CARDAPIO MONEY
) 


CREATE TABLE TB_ITEM_VENDA (
COD_ITEM_VENDA INT PRIMARY KEY IDENTITY (1,1),
COD_UTILIDADE_COMANDA INT REFERENCES TB_UTILIDADE_COMANDA(COD_UTILIDADE_COMANDA),
CPF_FUNC VARCHAR(14) REFERENCES TB_FUNCIONARIO (CPF_FUNC),
COD_CARDAPIO INT REFERENCES TB_CARDAPIO (COD_CARDAPIO),
COD_PRODUTO INT REFERENCES TB_PRODUTO (COD_PRODUTO)
)



